I use current script to run in console of google meet to allow copy caption text
currently, I am opening google meet in selenium, so you can use selenium mcp server to debug and test javascript code, you don't need to run tool navigate, or check_page_ready

for example this is caption block <div tabindex="0" role="region" aria-label="Captions" class="vNKgIf UDinHf" jscontroller="KPn5nb" jsaction="ffrh3d:NkE7Cc;WQWOEb:QQaxdb;O2Euof:QQaxdb;JIbuQc:N57abc(Xke7ne)"><div class="nMcdL bj4p3b     "><div class="adE6rb"><img class="Z6byG r6DyN" alt="" src="https://lh3.googleusercontent.com/mm/ALrkI7o95H-1_N5RKu-rtm6RVfojrJH0XfHFKkDV6KfsQ4ehmwrwAid_Mf0HyNSajMYDobUxfw" data-iml="8554"><div class="KcIKyf jxFHg "><span class="NWpY1d">You</span></div></div><div class="ygicle VbkSUe">You come up. You can do him. Let you so much but you let me so tired. so, We go. </div></div><div class="IMKgW"><div class="VfPpkd-dgl2Hf-ppHlrf-sM5MNb" data-is-touch-wrapper="true"><button class="UywwFc-LgbsSe UywwFc-LgbsSe-OWXEXe-Bz112c-M1Soyc UywwFc-LgbsSe-OWXEXe-dgl2Hf UywwFc-StrnGf-YYd4I-VtOx3e" jscontroller="O626Fe" jsaction="click:h5M12e;clickmod:h5M12e;pointerdown:FEiYhc;pointerup:mF5Elf;pointerenter:EX0mI;pointerleave:vpvbp;pointercancel:xyn4sd;contextmenu:xexox; focus:h06R8; blur:zjh6rb;mlnRJb:fLiPzd" jsname="Xke7ne" aria-label="Jump to most recent captions"><span class="OiePBf-zPjgPe"></span><span class="SXdXAb-BFbNVe"><span class="SXdXAb-ugnUJb"></span></span><span class="RBHQF-ksKsZd" jscontroller="LBaJxb" jsname="m9ZlFb"></span><span class="UywwFc-RLmnJb"></span><span jsname="Xr1QTb" class="UywwFc-kBDsod-Rtc0Jf UywwFc-kBDsod-Rtc0Jf-OWXEXe-M1Soyc"><i class="quRWN-Bz112c google-symbols notranslate" aria-hidden="true">arrow_downward</i></span><span jsname="V67aGc" class="UywwFc-vQzf8d" aria-hidden="true">Jump to bottom</span><span jsname="UkTUqb" class="UywwFc-kBDsod-Rtc0Jf UywwFc-kBDsod-Rtc0Jf-OWXEXe-UbuQg"></span></button></div></div></div>
there are a list of direct child div with class = nMcdL bj4p3b     , each block is a caption block of each user in the meeting, it include:
div class=adE6rb is the invisible block holding avatar and name of speaker
div class=ygicle VbkSUe is the caption text block

the script update style of div of speaker name and avatar to be able to copy the first line in div of caption text, it works, I can copy the fisrt line of caption text
the problem is now I cannot see speaker name and avatar, can you help me to fix it, I want to see speaker name and avatar, and I can copy the first line of caption text